from __future__ import annotations

import argparse
import csv
from pathlib import Path

GRADE_DEFINITIONS = [
    ("A+", "Immutable governance execution or consensus record suitable for treatment timing."),
    ("A", "Immutable technical record or pinned scholarly method."),
    ("A-", "Immutable user action or high-quality indexed record requiring a completeness check."),
    ("B+", "Official protocol chronology, documentation, or current-state interface."),
    ("B", "Official public-intent record or delivery channel with material access risk."),
    ("B-", "Useful validation delivery with narrow range or reliability constraints."),
]


def read_csv(path: Path) -> list[dict[str, str]]:
    with path.open(newline="", encoding="utf-8") as handle:
        return list(csv.DictReader(handle))


def markdown_cell(value: str) -> str:
    return " ".join(value.replace("|", "\\|").split())


def latex_escape(value: str) -> str:
    replacements = {
        "\\": r"\textbackslash{}",
        "&": r"\&",
        "%": r"\%",
        "$": r"\$",
        "#": r"\#",
        "_": r"\_",
        "{": r"\{",
        "}": r"\}",
        "~": r"\textasciitilde{}",
        "^": r"\textasciicircum{}",
    }
    return "".join(replacements.get(char, char) for char in value)


def latex_public_link(url: str) -> str:
    # Keep the complete URL in the hyperlink target while using a compact label.
    # The canonical CSV and generated Markdown retain the literal URL for audit.
    return rf"\href{{{url}}}{{public source}}"


def latex_timestamp(value: str) -> str:
    if "T" not in value:
        return latex_escape(value)
    date, time = value.split("T", maxsplit=1)
    return latex_escape(date) + r"\newline " + latex_escape(time)


def render_markdown(
    events: list[dict[str, str]],
    sources: list[dict[str, str]],
) -> str:
    lines = [
        "# Source and treatment audit",
        "",
        "The grade records what a source can prove. Delivery quality is graded separately",
        "because immutable evidence can still arrive through a throttled or unstable endpoint.",
        "",
        "## Grade definitions",
        "",
        "| Grade | Evidentiary meaning |",
        "|---|---|",
    ]
    lines.extend(f"| {grade} | {meaning} |" for grade, meaning in GRADE_DEFINITIONS)
    lines.extend(
        [
            "",
            "Only the six A+ governance-controlled activation transactions marked **Yes**",
            "below qualify as primary treatment dates. Forum posts define anticipation;",
            "technical transactions define readiness; first-user actions validate availability.",
            "",
            f"## Complete event ledger ({len(events)} records)",
            "",
            "| UTC | Chain | Event | Source type | Grade | Public source | Causal use | Primary |",
            "|---|---|---|---|---:|---|---|---:|",
        ]
    )
    for row in events:
        link = f"[verify]({row['source_url']})"
        cells = [
            row["event_time_utc"],
            row["chain"],
            row["event"],
            row["source_type"],
            row["evidence_tier"],
            link,
            row["causal_use"],
            row["primary_treatment"],
        ]
        lines.append("| " + " | ".join(markdown_cell(value) for value in cells) + " |")
    lines.extend(
        [
            "",
            f"## Complete acquisition catalog ({len(sources)} sources)",
            "",
            "| Source | Scope | Evidence | Delivery | Trust and limitation | Public URL | Access |",
            "|---|---|---:|---:|---|---|---|",
        ]
    )
    for row in sources:
        trust = f"{row['trustworthiness']} Limit: {row['limitation']}"
        cells = [
            row["source_id"],
            row["scope"],
            row["evidence_grade"],
            row["delivery_grade"],
            trust,
            f"[source]({row['public_url']})",
            row["access_requirement"],
        ]
        lines.append("| " + " | ".join(markdown_cell(value) for value in cells) + " |")
    lines.extend(
        [
            "",
            "## Machine-readable sources",
            "",
            "- `data/metadata/event_source_audit.csv`",
            "- `data/metadata/source_catalog.csv`",
            "",
            "Do not edit this Markdown table directly. Run `scripts/render_source_audit.py`",
            "after changing either canonical CSV.",
            "",
        ]
    )
    return "\n".join(lines)


def render_latex(
    events: list[dict[str, str]],
    sources: list[dict[str, str]],
) -> str:
    lines = [
        "% Generated by scripts/render_source_audit.py; do not edit by hand.",
        "% Requires: longtable, booktabs, array, url.",
        r"\clearpage",
        r"\suspendrefereelines",
        r"\begingroup",
        r"\setstretch{1.02}",
        r"\AVTableSetup",
        r"\setlength{\tabcolsep}{3pt}",
        (
            r"\begin{longtable}{p{0.145\linewidth}p{0.255\linewidth}"
            r"p{0.06\linewidth}p{0.115\linewidth}p{0.34\linewidth}}"
        ),
        r"\caption{Complete event-source ledger and causal role.}\label{tab:event-source-audit}\\",
        r"\toprule",
        r"\textbf{Time / chain} & \textbf{Event / source} & \textbf{G} & "
        r"\textbf{Record} & \textbf{Causal role} \\",
        r"\midrule",
        r"\endfirsthead",
        r"\multicolumn{5}{l}{\tablename\ \thetable\ continued}\\",
        r"\toprule",
        r"\textbf{Time / chain} & \textbf{Event / source} & \textbf{G} & "
        r"\textbf{Record} & \textbf{Causal role} \\",
        r"\midrule",
        r"\endhead",
        r"\bottomrule",
        r"\endfoot",
    ]
    for row in events:
        causal_use = row["causal_use"]
        causal_use_lower = causal_use.casefold()
        primary = (
            " Primary treatment."
            if row["primary_treatment"] == "Yes"
            and not all(term in causal_use_lower for term in ("primary", "treatment"))
            else ""
        )
        lines.append(
            " & ".join(
                [
                    latex_timestamp(row["event_time_utc"])
                    + r"\par\AVTableMeta{"
                    + latex_escape(row["chain"])
                    + "}",
                    r"\textbf{"
                    + latex_escape(row["event"])
                    + r"}\par\AVTableMeta{"
                    + latex_escape(row["source_type"])
                    + "}",
                    latex_escape(row["evidence_tier"]),
                    latex_public_link(row["source_url"]),
                    latex_escape(causal_use + primary),
                ]
            )
            + r" \\"
        )
    lines.extend(
        [
            r"\end{longtable}",
            r"\endgroup",
            "",
            r"\clearpage",
            r"\begingroup",
            r"\setstretch{1.02}",
            r"\AVTableSetup",
            r"\setlength{\tabcolsep}{3pt}",
            (
                r"\begin{longtable}{p{0.205\linewidth}p{0.09\linewidth}"
                r"p{0.52\linewidth}p{0.12\linewidth}}"
            ),
            (
                r"\caption{Complete acquisition-source catalog and delivery-risk audit.}"
                r"\label{tab:source-catalog}\\"
            ),
            r"\toprule",
            r"\textbf{Source / scope} & \textbf{E/D} & "
            r"\textbf{Trust and limitation} & \textbf{Record} \\",
            r"\midrule",
            r"\endfirsthead",
            r"\multicolumn{4}{l}{\tablename\ \thetable\ continued}\\",
            r"\toprule",
            r"\textbf{Source / scope} & \textbf{E/D} & "
            r"\textbf{Trust and limitation} & \textbf{Record} \\",
            r"\midrule",
            r"\endhead",
            r"\bottomrule",
            r"\endfoot",
        ]
    )
    for row in sources:
        trust = f"{row['trustworthiness']} Limit: {row['limitation']}"
        lines.append(
            " & ".join(
                [
                    rf"\path{{{row['source_id']}}}"
                    + r"\par\AVTableMeta{Scope: "
                    + latex_escape(row["scope"])
                    + "}",
                    latex_escape(row["evidence_grade"])
                    + "/"
                    + latex_escape(row["delivery_grade"]),
                    latex_escape(trust),
                    latex_public_link(row["public_url"]),
                ]
            )
            + r" \\"
        )
    lines.extend(
        [
            r"\end{longtable}",
            r"\endgroup",
            r"\resumerefereelines",
            (
                r"\noindent\AVTableNoteFont Every displayed source label is a live hyperlink "
                r"to the complete public URL. Literal URLs, access requirements, trust "
                r"statements, and limitations are preserved in the canonical CSV files "
                r"and the generated Markdown audit."
            ),
            "",
        ]
    )
    return "\n".join(lines)


def main() -> None:
    parser = argparse.ArgumentParser(description="Render source audit tables from canonical CSVs")
    parser.add_argument("--root", default=".", help="Repository root")
    args = parser.parse_args()
    root = Path(args.root).resolve()
    events = read_csv(root / "data/metadata/event_source_audit.csv")
    sources = read_csv(root / "data/metadata/source_catalog.csv")
    if len(events) != 31 or len(sources) != 21:
        raise ValueError("Expected 31 event records and 21 acquisition sources")
    (root / "docs/SOURCE_AUDIT.md").write_text(render_markdown(events, sources), encoding="utf-8")
    appendix = root / "paper/appendix/source_audit_tables.tex"
    appendix.parent.mkdir(parents=True, exist_ok=True)
    appendix.write_text(render_latex(events, sources), encoding="utf-8")


if __name__ == "__main__":
    main()
