#!/usr/bin/env python3
"""Render paper assets from the frozen Arbitrum--Gnosis benchmark outputs."""
from __future__ import annotations

import csv
import json
from collections.abc import Iterable
from pathlib import Path

ROOT = Path(__file__).resolve().parents[1]
OUTPUT = ROOT / "outputs/real_v6/arbitrum_gnosis_did_mvp"
PANEL = OUTPUT / "common_calendar_panel.csv"
ESTIMATES = OUTPUT / "estimates.csv"
PRETRENDS = OUTPUT / "pretrend_diagnostics.csv"
PLACEBOS = OUTPUT / "preperiod_placebos.csv"
SUMMARY = OUTPUT / "summary.json"

MAIN_TABLE = ROOT / "paper/tables/tab07_arbitrum_gnosis_benchmark.tex"
HORIZON_TABLE = ROOT / "paper/tables/tabA_arbitrum_gnosis_horizons.tex"
DIAGNOSTIC_TABLE = ROOT / "paper/tables/tabA_arbitrum_gnosis_diagnostics.tex"
FIGURE = ROOT / "paper/figures/fig07_arbitrum_gnosis_benchmark.tex"

OUTCOMES = {
    "log_active_beneficiary_addresses": "Log active position-holder addresses",
    "beneficiary_hhi": "Position-holder-event HHI",
}


def read_csv(path: Path) -> list[dict[str, str]]:
    with path.open(newline="", encoding="utf-8") as stream:
        return list(csv.DictReader(stream))


def validate_inputs(
    panel: list[dict[str, str]],
    estimates: list[dict[str, str]],
    summary: dict[str, object],
) -> None:
    if len(panel) != 66:
        raise ValueError(f"expected 66 common-calendar rows, found {len(panel)}")
    if {row["chain"] for row in panel} != {"Arbitrum", "Gnosis"}:
        raise ValueError("benchmark panel must contain exactly Arbitrum and Gnosis")
    for chain in ("Arbitrum", "Gnosis"):
        weeks = sorted(int(row["event_week"]) for row in panel if row["chain"] == chain)
        if weeks != list(range(-16, 17)):
            raise ValueError(f"{chain} event-week support is incomplete")
    if {row["causal_status"] for row in panel} != {"diagnostic_not_causal"}:
        raise ValueError("benchmark panel opened a causal claim unexpectedly")
    expected_pairs = {(outcome, horizon) for outcome in OUTCOMES for horizon in (8, 12, 16)}
    observed_pairs = {
        (row["outcome_id"], int(row["post_horizon"])) for row in estimates
    }
    if observed_pairs != expected_pairs:
        raise ValueError("benchmark horizon grid is incomplete or has drifted")
    if summary.get("common_calendar_panel_rows") != 66:
        raise ValueError("summary row count does not match the frozen panel")
    if summary.get("causal_estimate_produced") is not False:
        raise ValueError("frozen benchmark must not report a causal estimate")


def by_outcome_horizon(
    estimates: list[dict[str, str]], outcome: str, horizon: int
) -> dict[str, str]:
    rows = [
        row
        for row in estimates
        if row["outcome_id"] == outcome and int(row["post_horizon"]) == horizon
    ]
    if len(rows) != 1:
        raise ValueError(f"expected one estimate for {outcome} at horizon {horizon}")
    return rows[0]


def signed(value: str, digits: int) -> str:
    return f"{float(value):+.{digits}f}"


def interval(row: dict[str, str], digits: int) -> str:
    return f"[{float(row['ci_lower']):.{digits}f}, {float(row['ci_upper']):.{digits}f}]"


def render_main_table(estimates: list[dict[str, str]]) -> str:
    rows = []
    for outcome, digits in (
        ("log_active_beneficiary_addresses", 4),
        ("beneficiary_hhi", 5),
    ):
        row = by_outcome_horizon(estimates, outcome, 16)
        rows.append(
            f"{OUTCOMES[outcome]} & {signed(row['arbitrum_change'], digits)} & "
            f"{signed(row['gnosis_change'], digits)} & "
            f"\\textbf{{{signed(row['difference_in_changes_arbitrum_minus_gnosis'], digits)}}} "
            f"& {interval(row, digits)} \\\\"
        )
    return "\n".join(
        [
            "% Generated by scripts/render_real_v6_gnosis_paper_assets.py; do not edit.",
            r"\begin{table*}[t]",
            r"\centering",
            r"\caption{Arbitrum--Gnosis descriptive difference-in-changes decomposition.}",
            r"\label{tab:arbitrum-gnosis-benchmark}",
            r"\AVTableSetup",
            r"\begin{tabularx}{0.99\textwidth}{"
            r">{\raggedright\arraybackslash}X"
            r"*{4}{>{\centering\arraybackslash}X}}",
            r"\toprule",
            r"\AVTableHeader",
            r"\textbf{Outcome} & \textbf{Arbitrum change} & \textbf{Gnosis change} & "
            r"\textbf{Difference in changes} & \textbf{Descriptive NW range} \\",
            r"\midrule",
            *rows,
            r"\bottomrule",
            r"\end{tabularx}",
            r"\begin{minipage}{0.97\textwidth}",
            r"\AVTableNoteFont\emph{Notes:} The clean pre-period is weeks $-16$ to $-9$; "
            r"weeks $-8$ to $-1$ "
            r"and week 0 are excluded; the post-period is weeks $+1$ to $+16$. "
            r"The last column is a normal-approximation diagnostic range based on "
            r"calendar-aware Newey--West standard errors with lag 3; it is not a confidence "
            r"interval for a treatment effect. Position holders are protocol-observed "
            r"addresses, not verified economic actors. The negative HHI contrast means "
            r"that HHI rose less on Arbitrum than on "
            r"Gnosis; it does not mean that Arbitrum HHI fell in absolute terms.",
            r"\end{minipage}",
            r"\end{table*}",
            "",
        ]
    )


def render_horizon_table(estimates: list[dict[str, str]]) -> str:
    rows = []
    for outcome, digits in (
        ("log_active_beneficiary_addresses", 4),
        ("beneficiary_hhi", 5),
    ):
        for horizon in (8, 12, 16):
            row = by_outcome_horizon(estimates, outcome, horizon)
            rows.append(
                f"{OUTCOMES[outcome]} & $+{horizon}$ & "
                f"{signed(row['arbitrum_change'], digits)} & "
                f"{signed(row['gnosis_change'], digits)} & "
                f"{signed(row['difference_in_changes_arbitrum_minus_gnosis'], digits)} & "
                f"{interval(row, digits)} \\\\"
            )
    return "\n".join(
        [
            "% Generated by scripts/render_real_v6_gnosis_paper_assets.py; do not edit.",
            r"\begin{table}[!ht]",
            r"\centering",
            r"\caption{Descriptive contrasts across alternative post-window horizons.}",
            r"\label{tab:arbitrum-gnosis-horizons}",
            r"\AVTableSetup",
            r"\begin{tabularx}{0.98\linewidth}{"
            r">{\raggedright\arraybackslash}X"
            r"*{5}{>{\centering\arraybackslash}X}}",
            r"\toprule",
            r"\AVTableHeader",
            r"\textbf{Outcome} & \textbf{Through week} & \textbf{Arb.} & \textbf{Gnosis} "
            r"& \textbf{Diff. in changes} & \textbf{NW diagnostic} \\",
            r"\midrule",
            *rows,
            r"\bottomrule",
            r"\end{tabularx}",
            r"\begin{minipage}{0.96\linewidth}",
            r"\AVTableNoteFont\emph{Notes:} The clean pre-period remains weeks $-16$ to $-9$ "
            r"for every row. Calendar spacing is preserved in the Newey--West calculation. "
            r"The ranges are descriptive normal approximations, not treatment-effect "
            r"confidence intervals.",
            r"\end{minipage}",
            r"\end{table}",
            "",
        ]
    )


def render_diagnostic_table(
    pretrends: list[dict[str, str]], placebos: list[dict[str, str]]
) -> str:
    lines = [
        "% Generated by scripts/render_real_v6_gnosis_paper_assets.py; do not edit.",
        r"\begin{table}[!ht]",
        r"\centering",
        r"\caption{Differential pre-trends and pre-period placebo contrasts.}",
        r"\label{tab:arbitrum-gnosis-diagnostics}",
        r"\AVTableSetup",
        r"\begin{tabular}{llrrr}",
        r"\toprule",
        r"\AVTableHeader",
        r"\textbf{Outcome} & \textbf{Diagnostic} & \textbf{Estimate} & "
        r"\textbf{Lower} & \textbf{Upper} \\",
        r"\midrule",
    ]
    for row in pretrends:
        digits = 5 if row["outcome_id"] == "beneficiary_hhi" else 5
        lines.append(
            f"{OUTCOMES[row['outcome_id']]} & gap slope/week & "
            f"{signed(row['gap_slope_per_event_week'], digits)} & "
            f"{float(row['ci_lower']):.{digits}f} & {float(row['ci_upper']):.{digits}f} \\\\"
        )
    lines.append(r"\midrule")
    for row in placebos:
        digits = 5 if row["outcome_id"] == "beneficiary_hhi" else 4
        lines.append(
            f"{OUTCOMES[row['outcome_id']]} & placebo week {int(row['pseudo_event_week']):+d} "
            f"& {signed(row['gap_change'], digits)} & -- & -- \\\\"
        )
    lines.extend(
        [
            r"\bottomrule",
            r"\end{tabular}",
            r"\begin{minipage}{0.96\linewidth}",
            r"\AVTableNoteFont\emph{Notes:} Slope intervals use Newey--West lag 2. "
            r"Placebos compare two weeks before and after the pseudo-event within the "
            r"pre-window period. The nonzero slopes show that Gnosis is not a credible "
            r"counterfactual for an average treatment effect.",
            r"\end{minipage}",
            r"\end{table}",
            "",
        ]
    )
    return "\n".join(lines)


def coordinates(
    panel: Iterable[dict[str, str]], chain: str, field: str, digits: int
) -> str:
    selected = sorted(
        (row for row in panel if row["chain"] == chain),
        key=lambda row: int(row["event_week"]),
    )
    return " ".join(
        f"({int(row['event_week'])},{float(row[field]):.{digits}f})" for row in selected
    )


def render_figure(panel: list[dict[str, str]]) -> str:
    arb_log = coordinates(panel, "Arbitrum", "log_active_beneficiary_addresses", 6)
    gno_log = coordinates(panel, "Gnosis", "log_active_beneficiary_addresses", 6)
    arb_hhi = coordinates(panel, "Arbitrum", "beneficiary_hhi", 7)
    gno_hhi = coordinates(panel, "Gnosis", "beneficiary_hhi", 7)
    return "\n".join(
        [
            "% Generated by scripts/render_real_v6_gnosis_paper_assets.py; do not edit.",
            r"\begin{figure*}[t]",
            r"\centering",
            r"\suspendrefereelines",
            r"\begin{tikzpicture}[font=\AVFigureFont]",
            r"\begin{groupplot}[",
            r"group style={group size=2 by 1,horizontal sep=13mm},",
            r"width=0.455\textwidth,height=5.2cm,",
            r"xmin=-16,xmax=16,xtick={-16,-8,0,8,16},",
            r"xlabel={Event week},grid=both,minor tick num=1,",
            r"grid style={draw=AVRule!65,line width=0.25pt},",
            r"axis line style={draw=AVNavy!75},tick label style={font=\AVFigureSmallFont},",
            r"label style={font=\AVFigureFont},title style={font=\AVFigureTitleFont},",
            r"legend style={font=\AVFigureSmallFont,draw=none,fill=none,",
            r"at={(0.5,1.27)},anchor=south,legend columns=2,legend cell align=left},",
            r"every axis plot/.append style={line width=1pt}",
            r"]",
            r"\nextgroupplot[title={A. Log participation},",
            r"ylabel={$\log(1+N_t^{p})$}]",
            rf"\addplot+[color=AVBlue,mark=*,mark size=1.3pt] coordinates {{{arb_log}}};",
            r"\addlegendentry{Arbitrum}",
            r"\addplot+[color=AVOrange,dashed,mark=square*,mark size=1.2pt] "
            rf"coordinates {{{gno_log}}};",
            r"\addlegendentry{Gnosis}",
            r"\draw[AVSlate,densely dashed,line width=0.8pt] "
            r"(axis cs:0,\pgfkeysvalueof{/pgfplots/ymin}) -- "
            r"(axis cs:0,\pgfkeysvalueof{/pgfplots/ymax});",
            r"\nextgroupplot[title={B. Pool-event-frequency HHI},",
            r"ylabel={Position-holder-event HHI},scaled y ticks=false,",
            r"ticklabel style={/pgf/number format/fixed,/pgf/number format/precision=3}]",
            rf"\addplot+[color=AVBlue,mark=*,mark size=1.3pt] coordinates {{{arb_hhi}}};",
            r"\addplot+[color=AVOrange,dashed,mark=square*,mark size=1.2pt] "
            rf"coordinates {{{gno_hhi}}};",
            r"\draw[AVSlate,densely dashed,line width=0.8pt] "
            r"(axis cs:0,\pgfkeysvalueof{/pgfplots/ymin}) -- "
            r"(axis cs:0,\pgfkeysvalueof{/pgfplots/ymax});",
            r"\end{groupplot}",
            r"\end{tikzpicture}",
            r"\resumerefereelines",
            r"\caption{Raw weekly Arbitrum and Gnosis series on the common UTC calendar. "
            r"Week 0 (vertical dashed line) is the verified Arbitrum GHO activation week, "
            r"2 July 2024. The figure displays observed address-level series; it is a "
            r"failed-donor diagnostic, not a causal event-study estimate.}",
            r"\label{fig:arbitrum-gnosis-benchmark}",
            r"\end{figure*}",
            "",
        ]
    )


def main() -> None:
    panel = read_csv(PANEL)
    estimates = read_csv(ESTIMATES)
    pretrends = read_csv(PRETRENDS)
    placebos = read_csv(PLACEBOS)
    summary = json.loads(SUMMARY.read_text(encoding="utf-8"))
    validate_inputs(panel, estimates, summary)
    assets = {
        MAIN_TABLE: render_main_table(estimates),
        HORIZON_TABLE: render_horizon_table(estimates),
        DIAGNOSTIC_TABLE: render_diagnostic_table(pretrends, placebos),
        FIGURE: render_figure(panel),
    }
    for path, content in assets.items():
        path.parent.mkdir(parents=True, exist_ok=True)
        path.write_text(content, encoding="utf-8")
        print(path.relative_to(ROOT))


if __name__ == "__main__":
    main()
