#!/usr/bin/env python3
"""Render scale-aware topology diagnostics from the locked real-v5 summary."""
# ruff: noqa: E501
from __future__ import annotations

import json
from pathlib import Path

ROOT = Path(__file__).resolve().parents[1]
SUMMARY = ROOT / "outputs/real_v5/core_periphery/summary.json"
OUTPUT = ROOT / "paper/tables/tab05_real_v5_topology.tex"


def _percent(value: float, digits: int = 2) -> str:
    return f"{100.0 * value:.{digits}f}\\%"


def render(summary: dict[str, object]) -> str:
    chains = summary["chains"]
    eth = chains["Ethereum"]
    arb = chains["Arbitrum"]

    def diagnostics(chain: dict[str, object]) -> dict[str, float]:
        n = int(chain["directed_node_count"])
        hhi = float(chain["pagerank_hhi"])
        be = int(chain["borgatti_everett"]["core_node_count"])
        inside = int(chain["method_agreement"]["be_nodes_in_maximum_k_core"])
        persistent = int(chain["temporal_core"]["addresses_with_persistence_at_least_half"])
        return {
            "scaled_pagerank_hhi": n * hhi,
            "effective_pagerank_fraction": 1.0 / (n * hhi),
            "maximum_core_share": float(chain["maximum_k_core_node_share"]),
            "be_containment": inside / be,
            "persistent_share": persistent / n,
        }

    e = diagnostics(eth)
    a = diagnostics(arb)
    end = r" \\"
    lines = [
        "% Generated by scripts/render_scale_adjusted_topology_table.py; do not edit.",
        r"\begin{table}[htbp]",
        r"\centering",
        r"\caption{Audited full-window address-role topology with scale diagnostics.}",
        r"\label{tab:real-v5-topology}",
        r"\AVTableSetup",
        r"\begin{tabularx}{0.94\linewidth}{Xrr}",
        r"\toprule",
        r"\AVTableHeader",
        r"\textbf{Measure} & \textbf{Ethereum} & \textbf{Arbitrum} \\",
        r"\midrule",
        r"\AVTableSubheader",
        r"\multicolumn{3}{l}{\emph{Scale and role assignment}} \\",
        f"Pool events & {int(eth['event_count']):,} & {int(arb['event_count']):,}" + end,
        f"Delegated or third-party events & {int(eth['delegated_event_count']):,} & {int(arb['delegated_event_count']):,}" + end,
        f"Role-network nodes & {int(eth['directed_node_count']):,} & {int(arb['directed_node_count']):,}" + end,
        f"Unique directed edges & {int(eth['directed_edge_count']):,} & {int(arb['directed_edge_count']):,}" + end,
        r"\addlinespace[2pt]",
        r"\AVTableSubheader",
        r"\multicolumn{3}{l}{\emph{Role-weight and scale-aware diagnostics}} \\",
        f"Raw action-side strength HHI & {float(eth['weighted_out_degree_hhi']):.4f} & {float(arb['weighted_out_degree_hhi']):.4f}" + end,
        f"Raw position-holder-side strength HHI & {float(eth['weighted_in_degree_hhi']):.4f} & {float(arb['weighted_in_degree_hhi']):.4f}" + end,
        f"Raw PageRank HHI & {float(eth['pagerank_hhi']):.6f} & {float(arb['pagerank_hhi']):.6f}" + end,
        f"PageRank HHI $\\times$ node count & {e['scaled_pagerank_hhi']:.4f} & {a['scaled_pagerank_hhi']:.4f}" + end,
        f"Effective PageRank-node fraction & {_percent(e['effective_pagerank_fraction'])} & {_percent(a['effective_pagerank_fraction'])}" + end,
        f"Maximum $k$-core share & {_percent(e['maximum_core_share'], 3)} & {_percent(a['maximum_core_share'], 3)}" + end,
        f"Persistent maximum-core share & {_percent(e['persistent_share'], 3)} & {_percent(a['persistent_share'], 3)}" + end,
        r"\addlinespace[2pt]",
        r"\AVTableSubheader",
        r"\multicolumn{3}{l}{\emph{Core-definition diagnostics}} \\",
        f"BE binary-core nodes (minimum allowed) & {int(eth['borgatti_everett']['core_node_count'])} & {int(arb['borgatti_everett']['core_node_count'])}" + end,
        f"BE nodes contained in maximum-$k$ core & {_percent(e['be_containment'], 0)} & {_percent(a['be_containment'], 0)}" + end,
        f"Rombach--$k$-core Spearman $\\rho$ & {float(eth['method_agreement']['rombach_k_core_spearman']):.3f} & {float(arb['method_agreement']['rombach_k_core_spearman']):.3f}" + end,
        r"\bottomrule",
        r"\end{tabularx}",
        r"\begin{tablenotes}[flushleft]",
        r"\AVTableNoteFont",
        r"\item \emph{Notes:} A directed edge runs from action-side to position-holder address and is weighted by Pool-event count. Self-directed events are excluded from topology. PageRank HHI has lower bound $1/n$; multiplying by $n$ gives 1 under a uniform distribution, and its reciprocal is the effective-node fraction. The two-node Borgatti--Everett (BE) solutions hit the algorithm's imposed minimum and are fully contained in the maximum-$k$ cores, so unequal-set Jaccard values are not interpreted as membership disagreement. Raw graph size and density differ; no scalar cross-chain structural ranking is claimed.",
        r"\end{tablenotes}",
        r"\end{table}",
        "",
    ]
    return "\n".join(lines)


def main() -> None:
    summary = json.loads(SUMMARY.read_text(encoding="utf-8"))
    OUTPUT.write_text(render(summary), encoding="utf-8")
    print(OUTPUT.relative_to(ROOT))


if __name__ == "__main__":
    main()
